blank_issues_enabled: false
contact_links:
  - name: Betaflight support
    url: https://github.com/betaflight/betaflight-configurator
    about: Use the official Betaflight channels for general Betaflight configuration support.
